version: '3'
services:
  kaddem:
    image: slimdrira/kaddem-backend:latest
    ports:
      - "8089:8089"
    networks:
      - app-network
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaddem
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge