version: '3.3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Ayouda123
      MYSQL_DATABASE: kaddem
      MYSQL_USER: mokhtar
      MYSQL_PASSWORD: Ayouda123
    ports:
      - "3306:3306"

  gestion-station-ski-backend:
    image: mokhtardocker11/kaddem-backend:latest  # Utiliser l'image correcte ici
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/kaddem?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: mokhtar
      SPRING_DATASOURCE_PASSWORD: Ayouda123
      SPRING_SERVER_PORT: 8089
